# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [5]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Python_mehak\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Python_mehak\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Python_mehak\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Python_mehak\\Li

#### 3. Create a null vector of size 10

In [14]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [3]:
arr=np.array([1,2,3,4])
print(arr.size*arr.itemsize)

16


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [17]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [18]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [20]:
arr=list(range(10,50))
print(arr)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]


#### 8.  Reverse a vector (first element becomes last)

In [21]:
arr=np.array([1,2,3,4,6])
arr[::-1]

array([6, 4, 3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
arr=np.array(range(0,9))
np.reshape(arr,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [40]:
arr=np.array([1,2,0,0,4,0])
lst=[]
for i in range(0,len(arr)):
    if arr[i]!=0:
        lst.append(i)
print(lst)

#np.nonzero(arr)

[0, 1, 4]


(array([0, 1, 4], dtype=int32),)

#### 11. Create a 3x3 identity matrix

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [45]:
arr=np.array(np.random.rand(27))
print(np.reshape(arr,(3,3,3)))

#np.random.random((3,3,3))

[[[0.72834667 0.7004837  0.10934072]
  [0.04727853 0.99889597 0.65995506]
  [0.03675868 0.7160165  0.85262586]]

 [[0.4372164  0.52112759 0.9675418 ]
  [0.41922337 0.64242908 0.45979636]
  [0.29413296 0.62889851 0.14328126]]

 [[0.71553081 0.43034497 0.76553394]
  [0.58453545 0.0846925  0.3171172 ]
  [0.99158424 0.46214075 0.98896186]]]


array([[[0.56120351, 0.42171392, 0.52536692],
        [0.22006142, 0.38084543, 0.44866642],
        [0.92167329, 0.024499  , 0.67666686]],

       [[0.47279645, 0.72271663, 0.05937011],
        [0.2144836 , 0.33579264, 0.04484447],
        [0.39360594, 0.24888768, 0.37888665]],

       [[0.19099886, 0.638107  , 0.33202953],
        [0.59690537, 0.33557162, 0.16981302],
        [0.04355953, 0.53753989, 0.25304401]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [4]:
arr=np.array(np.random.random((10,10)))
print(arr)
print(arr.min())
print(arr.max())

[[0.03103374 0.38459094 0.54722252 0.33560766 0.99167647 0.34847686
  0.68023061 0.46666307 0.07817946 0.56495145]
 [0.49226394 0.35994555 0.9836001  0.67443302 0.58148634 0.67382888
  0.77044828 0.93577296 0.37429346 0.0448569 ]
 [0.83963378 0.96974163 0.99256913 0.56991811 0.34009539 0.91567692
  0.24691153 0.76771974 0.91440295 0.81689981]
 [0.96946857 0.69960432 0.80421549 0.54110012 0.06430377 0.72493151
  0.03793125 0.56861891 0.09183788 0.27474472]
 [0.66370911 0.42661146 0.6256164  0.45411054 0.4847243  0.02255385
  0.58093114 0.07659418 0.41095175 0.83909053]
 [0.7056867  0.48180276 0.72779431 0.77515796 0.00736037 0.7518646
  0.10245818 0.55943151 0.31266187 0.45430416]
 [0.43659839 0.09905869 0.39501105 0.55686881 0.48339652 0.39406218
  0.53723697 0.16231217 0.5954351  0.86089687]
 [0.60810726 0.54536771 0.38601811 0.23752149 0.73441414 0.27342465
  0.23530047 0.66495117 0.50773355 0.57021525]
 [0.09575328 0.95063276 0.57684759 0.02797839 0.2733166  0.7009836
  0.51624406 0

#### 14. Create a random vector of size 30 and find the mean value

In [52]:
arr=np.random.random(30)
print(arr)
print(np.mean(arr))

[0.48546192 0.69598954 0.98589837 0.01418041 0.13072215 0.72223069
 0.64183952 0.18984678 0.34145903 0.24152914 0.65303229 0.1809812
 0.12437293 0.46285005 0.35070024 0.08035578 0.05400253 0.78044262
 0.22638108 0.98190351 0.3225256  0.65171819 0.41079665 0.86834243
 0.4393896  0.3107401  0.14877881 0.27013394 0.86174399 0.49192316]
0.4373424079049727


#### 15. Create a 2d array with 1 on the border and 0 inside

In [62]:
arr=np.ones((5,5))
print(arr)
arr[1:4,1:4]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [6]:
arr=np.ones((5,5))
print(arr)
np.pad(arr,pad_width=1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [7]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [25]:
arr=np.ones((8,8),int)
arr[::2,::2]=0
arr[1::2,1::2]=0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [26]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)