# Numpy

In [2]:
import numpy as np

In [8]:
#Creating an array
arr=np.array([[1,2],[3,4]])

print("print array\n",arr)
print("type of array",type(arr))
print("Dimensions array",arr.ndim)
print("no of rows * no of columns = ",arr.shape)
print("no of elements in array",arr.size)
print("data type of array",arr.dtype)

print array
 [[1 2]
 [3 4]]
type of array <class 'numpy.ndarray'>
Dimensions array 2
no of rows * no of columns =  (2, 2)
no of elements in array 4
data type of array int32


In [11]:
# creating array from list with type float
arr=np.array([[1,2,3],[4,5,6]],dtype="float")
print("Print array\n",arr)

# creating array from tuple
arr=np.array((1,2,3,4))
print("Array using tuple\n",arr)

# creating a 3X4 array with all zeros
arr=np.zeros((3,4))
print("Array with all zeroes\n",arr)

# create a constant value array of complex type
arr=np.full((3,3),5,dtype="complex")
print("Print array with complex data type\n",arr)

# create an array with random values
arr=np.random.random((3,3))
print("Array with random values\n",arr)

# create a sequence of integers from 0 to 30 with steps of 5
arr=np.arange(0,30,5)
print("Array\n",arr)

# create a sequence of 10 values in range 0 to 5
arr=np.linspace(0,5,10)
print("Array containing 10 values\n",arr)

# reshaping 3X4 array to 2X2X3 array
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print("Original array\n",arr)
print("Array reshape to 2*2*3\n",arr.reshape((2,2,3)))

      
# flatten array
arr=np.array([[1,2],[3,4]])
print("Original array\n",arr)
print("flatten array\n",arr.flatten())


Print array
 [[1. 2. 3.]
 [4. 5. 6.]]
Array using tuple
 [1 2 3 4]
Array with all zeroes
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Print array with complex data type
 [[5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j]]
Array with random values
 [[0.61537009 0.71127439 0.37286068]
 [0.82651689 0.28341757 0.33807594]
 [0.86620491 0.85427177 0.54864112]]
Array
 [ 0  5 10 15 20 25]
Array containing 10 values
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Original array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array reshape to 2*2*3
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Original array
 [[1 2]
 [3 4]]
flatten array
 [1 2 3 4]


In [16]:
# an examplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Array\n",arr)

# slicing
print("Array elements from 2nd row to end and from start col to 3rd col\n",arr[1:,:3])
print("Array elements from 2nd row to end and from start col to 3rd col after leaving one element\n",arr[1::2,:3:2])

# Elements at indices (0, 3), (1, 2), (2, 1), (3, 0)
# syntax is arr[[rows],[col]]
temp=arr[[0,1,2,3],[3,2,1,0]]
print("Elements at indices (0, 3), (1, 2), (2, 1), (3, 0)\n",temp)

# boolean array indexing example
cond=arr>0
temp=arr[cond]
print("Boolean array indexing example\n",temp)

Array
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array elements from 2nd row to end and from start col to 3rd col
 [[ 4.  -0.5  6. ]
 [ 2.6  0.   7. ]
 [ 3.  -7.   4. ]]
Array elements from 2nd row to end and from start col to 3rd col after leaving one element
 [[4. 6.]
 [3. 4.]]
Elements at indices (0, 3), (1, 2), (2, 1), (3, 0)
 [4. 6. 0. 3.]
Boolean array indexing example
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [28]:
a = np.array([1, 2, 5, 3])
print("Original array",a)

# add 1 to every element
print("After adding array",a+1)

# subtract 3 from each element
print("After subtracting",a-3)

# multiply each element by 10
print("After multiplication",a*10)

# square each element
print("Squaring",a**2)

# modify existing array
a=a*2
print("doubling",a)

# transpose of array using a.T or a.transpose()
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)
print("Transpose of array:\n", a.transpose())

Original array [1 2 5 3]
After adding array [2 3 6 4]
After subtracting [-2 -1  2  0]
After multiplication [10 20 50 30]
Squaring [ 1  4 25  9]
doubling [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


### Unary Operators:
--Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [30]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

# maximum element of array
print("Largest element is:", arr.max())
print("Row-wise maximum elements:", arr.max(axis = 1))

# minimum element of array
print("Column-wise minimum elements:", arr.min(axis = 0))

# sum of array elements
print("Sum of all array elements:", arr.sum())

# cumulative sum along each row
# for row axis=1 and for col axis=0
print("Cumulative sum along each row:\n", arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


### Binary operators: 
-- These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, *, etc. In case of +=, -=, *= operators, the exsisting array is modified.

In [31]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[4, 3], 
              [2, 1]])

# add arrays
print("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print("Array multiplication:\n", a*b)

# matrix multiplication
print("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


### Universal functions (ufunc): 
-- NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.
#### Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [32]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

# square root of array values
print("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


### Sorting array
-- There is a simple np.sort method for sorting NumPy arrays. Let's explore it a bit.

In [5]:
a = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])

# sorted array
print("Array elements in sorted order:\n", np.sort(a, axis = None))

# sort array row-wise
print("Row-wise sorted array:\n", np.sort(a, axis = 1))

# specify sort algorithm
print("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort'))

# example to show sorting of structured array
## set alias names for dtypes
# data type of name is s stands for string and 20 is maximum length of string
dtypes = [('name', 'S20'), ('grad_year', int), ('cgpa', float)]
## values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
## creating array
arr = np.array(values, dtype = dtypes)
print("\nArray sorted by names:\n", np.sort(arr, order = 'name'))
print("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


## Stacking and Splitting
Several arrays can be stacked together along different axes.

#### np.vstack: To stack arrays along vertical axis.

#### np.hstack: To stack arrays along horizontal axis.

#### np.column_stack: To stack 1-D arrays as columns into 2-D arrays.

#### np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [6]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# vertical stacking
print("Vertical stacking:\n", np.vstack((a, b)))

# horizontal stacking
print("\nHorizontal stacking:\n", np.hstack((a, b)))

c = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))

# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


### For splitting, we have these fuctions:

#### np.hsplit: Split array along horizontal axis.

#### np.vsplit: Split array along vertical axis.

#### np.array_split: Split array along specified axis.

In [10]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

# horizontal splitting - colwise
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))

# vertical splitting - rowwise
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


### Some More Numpy Functions - Statistics
-- min, max
-- mean
-- median
-- average
-- variance
-- standard devidation

In [11]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [12]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [13]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

# weighted mean => n1*w1 + n2*w2 / n1+n2 

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev= np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


### Numpy Random Module
#### rand : Random values in a given shape.
#### randn : Return a sample (or samples) from the “standard normal” distribution.
#### randint : Return random integers from low (inclusive) to high (exclusive).
#### random : Return random floats in the half-open interval [0.0, 1.0)
####  choice : Generates a random sample from a given 1-D array
####  Shuffle : Shuffles the contents of a sequence

In [22]:
a = np.arange(10) + 5
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
